import turtle
import os

win=turtle.Screen()
win.bgcolor('light blue')
t=turtle.Pen()
t.speed(1)
t.color(1,0,0)
t.begin_fill()
t.forward(55)
t.left(90)
t.forward(70)
t.right(160)
t.forward(78)
t.left(70)	
t.forward(50)
t.left(116)
t.forward(90)
t.right(115)
t.forward(30)
t.left(90)
t.forward(60)
t.left(90)
t.forward(115)
t.end_fill()
turtle.getscreen()._root.mainloop()